//
//  ProductListModels.swift
//  TestProject
//
//  Created by GOR GALSTYAN on 2021-02-05.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProductList
{
  // MARK: Use cases


    struct Product: Decodable {
        var code: String
        var image: String
        var name: String
        var price: String
        var type: String
    }
  
    enum Fetch
    {
        struct Request
        {
            var name: String
        }
        struct Response
        {
            var statusCode: Int
            var errorMessage: String
            var data: [Product]
        }
        struct ViewModel
        {
            var status: Int
            var data: [Product]
        }
    }
}
