//
//  ProductListInteractor.swift
//  TestProject
//
//  Created by GOR GALSTYAN on 2021-02-05.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductListBusinessLogic
{
  func fetchData(request: ProductList.Fetch.Request)
}

protocol ProductListDataStore
{
  //var name: String { get set }
}

class ProductListInteractor: ProductListBusinessLogic, ProductListDataStore
{
  var presenter: ProductListPresentationLogic?
  var worker: ProductListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func fetchData(request: ProductList.Fetch.Request)
  {
    worker = ProductListWorker()
    worker?.getProductList() { result in
        switch result {
        case .failure( _):
            break; // TODO: handle error here
        case .success(let response):
          DispatchQueue.main.async {
            let response = ProductList.Fetch.Response(statusCode: 1, errorMessage: "", data: response.entries)
            self.presenter?.presentSomething(response: response)
          }
        }
    }
  }
}
