//
//  ProductListPresenter.swift
//  TestProject
//
//  Created by GOR GALSTYAN on 2021-02-05.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductListPresentationLogic
{
  func presentSomething(response: ProductList.Fetch.Response)
}

class ProductListPresenter: ProductListPresentationLogic
{
  weak var viewController: ProductListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ProductList.Fetch.Response)
  {
    let viewModel = ProductList.Fetch.ViewModel(status: 0, data: response.data)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
